#!/usr/bin/env python3
"""
ZES Downloader Daemon v3 — Full-featured web-to-ZIP with design analysis.
Clones websites preserving original structure, generates DESIGN.md + CRAWL_REPORT.md.

Usage:
    python3 srccode/downloader-daemon.py              # Daemon + HTTP server
    python3 srccode/downloader-daemon.py --url https://example.com  # Direct clone
    python3 srccode/downloader-daemon.py --once       # Process one batch
    python3 srccode/downloader-daemon.py --serve-only # HTTP server only

Requires: zip, requests
"""
import os, sys, json, time, logging, subprocess, tempfile, shutil, threading, re, hashlib, io
import urllib.request, urllib.error
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse, urljoin
from datetime import datetime, UTC

logging.basicConfig(level=logging.INFO, format='[DL] %(message)s')
log = logging.getLogger('downloader')

WORKER_URL = os.environ.get('WORKER_URL', 'https://api.zes.codes')
AUTH_TOKEN = os.environ.get('DL_AUTH_TOKEN', 'zes-cf-push-2024')
DL_DIR = Path(os.environ.get('DL_DIR', os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'downloads')))
DL_DIR.mkdir(parents=True, exist_ok=True)
SERVE_PORT = int(os.environ.get('DL_SERVE_PORT', 9090))

# ─── API ────────────────────────────────────────────────────────────────────

def api_get(path):
    req = urllib.request.Request(f'{WORKER_URL}{path}')
    req.add_header('X-Auth-Token', AUTH_TOKEN)
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())

def api_post(path, data):
    try:
        req = urllib.request.Request(
            f'{WORKER_URL}{path}',
            data=json.dumps(data).encode(),
            headers={'Content-Type': 'application/json', 'X-Auth-Token': AUTH_TOKEN},
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        log.debug(f"API {path}: {e.code} (offline or unauth)")
        return None
    except Exception as e:
        log.debug(f"API {path}: {e}")
        return None

def update_status(dl_id, **kw):
    try:
        api_post('/api/download/update', {'id': dl_id, **kw})
    except Exception:
        pass

# ─── HTML/CSS Parsing ───────────────────────────────────────────────────────

def detect_tech_stack(html: str) -> list:
    stack = []
    checks = [
        ('React/Next.js', ['__NEXT_DATA__', '__next_f', 'next-route-announcer', '/_next/static']),
        ('Vue.js', ['__VUE__', 'vue-', 'data-v-']),
        ('Angular', ['ng-version', 'ng-app']),
        ('Tailwind CSS', ['tailwind', 'dark:', 'sm:', 'md:', 'lg:', 'xl:', '2xl:']),
        ('Bootstrap', ['bootstrap', 'col-', 'col-md-', 'col-lg-']),
        ('Shopify', ['myshopify', '/cdn/shop']),
        ('jQuery', ['jquery', 'jQuery']),
        ('Webpack', ['webpack', '__webpack_require__']),
        ('Turbopack', ['turbopack']),
    ]
    for name, patterns in checks:
        for p in patterns:
            if p in html:
                stack.append(name)
                break
    return stack

def extract_colors(css_text: str) -> dict:
    colors = {}
    for m in re.finditer(r'--([\w-]+)\s*:\s*([^;]+);', css_text):
        name, val = m.group(1).strip(), m.group(2).strip()
        if any(c in name.lower() for c in ['color', 'accent', 'background', 'border', 'card', 'chart']):
            colors[f'--{name}'] = val
    return dict(list(colors.items())[:50])

def extract_fonts(css_text: str) -> list:
    fonts = []
    for m in re.finditer(r'@font-face\s*\{([^}]+)\}', css_text, re.I):
        block = m.group(1)
        family = re.search(r'font-family\s*:\s*["\']?([^;"\']+)', block, re.I)
        if family:
            fonts.append(family.group(1).strip())
    return fonts

def generate_design_md(url: str, css_text: str, tech_stack: list, total_files: int) -> str:
    colors = extract_colors(css_text)
    fonts = extract_fonts(css_text)
    
    lines = [f"# DESIGN.md — {url}", "",
             f"*Auto-generated by ZES Downloader on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}*",
             "", "---", ""]
    
    lines.append("## 🏗 Platform / CMS")
    for t in tech_stack:
        lines.append(f"- **{t}**")
    lines.append("")
    
    if colors:
        lines.append("## 🎨 Color Palette")
        lines.append("| Token | Value |")
        lines.append("|-------|-------|")
        for k, v in colors.items():
            lines.append(f"| `{k}` | `{v}` |")
        lines.append("")
    
    if fonts:
        lines.append("## 🔤 Typography")
        for f in fonts:
            lines.append(f"- {f}")
        lines.append("")
    
    lines.append("## 🧩 Component Patterns")
    for p, pat in [('Header/Navigation', r'<header'), ('Footer', r'<footer'),
                    ('Content Sections', r'<section'), ('Forms', r'<form'),
                    ('Navigation Menu', r'<nav'), ('Buttons/CTAs', r'<button'),
                    ('Images/Media', r'<img'), ('Grid Layouts', r'class="[^"]*grid'),
                    ('Flexbox Layouts', r'class="[^"]*flex'), ('Cards', r'class="[^"]*card')]:
        lines.append(f"- **{p}**")
    lines.append("")
    
    lines.append("---")
    lines.append("## 📐 Layout Analysis")
    lines.append(f"- Total HTML size: N/A")
    lines.append(f"- Total CSS analyzed: {len(css_text):,} bytes")
    lines.append(f"- Total files archived: {total_files}")
    lines.append(f"- Design tokens extracted: {len(colors)}")
    lines.append(f"- Font families detected: {len(fonts)}")
    lines.append("")
    return '\n'.join(lines)

def generate_crawl_report(url: str, pages: int, files: int, tech_stack: list) -> str:
    return f"""# ZES Crawl Report
Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}
Source URL: {url}
Mode: full - Maximum depth crawl - design + research combined

## Summary
- Pages Crawled: {pages}
- Total Files: {files}
- Tech Stack: {', '.join(tech_stack) if tech_stack else 'Unknown'}

## Tech Stack
{chr(10).join(f'- {t}' for t in tech_stack) if tech_stack else '- Unknown'}

## Mode Configuration
- Crawl Depth: 5
- Include Patterns: .*
- Exclude Patterns: /\\. (dotfiles)
"""

# ─── Smart Clone Engine ─────────────────────────────────────────────────────

HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
    "Accept": "text/html,application/xhtml+xml,*/*;q=0.8",
}

def page_to_rel_path(page_url: str) -> str:
    """Convert page URL to filesystem path with /index.html suffix."""
    parsed = urlparse(page_url)
    path = parsed.path.rstrip('/')
    if not path:
        return 'index.html'
    return path.lstrip('/') + '/index.html'

def asset_to_rel_path(asset_url: str) -> str:
    """Convert asset URL to filesystem path preserving original structure."""
    parsed = urlparse(asset_url)
    path = parsed.path.lstrip('/') or 'index'
    # Strip query params from path, keep them in filename for cache busters
    return path

def clone_site(url: str, out_dir: Path) -> dict:
    """Clone a website preserving original structure, return stats."""
    import requests as req_lib
    requests = req_lib

    downloaded = set()
    css_texts = []
    visited = set()
    pages_crawled = 0
    all_css_text = ''
    orig_domain = urlparse(url).netloc

    def dl_asset(asset_url: str) -> Path | None:
        if asset_url in downloaded or not asset_url.startswith('http'):
            return None
        downloaded.add(asset_url)
        try:
            r = requests.get(asset_url, headers=HEADERS, timeout=15, stream=True)
            r.raise_for_status()
            rel = asset_to_rel_path(asset_url)
            local = out_dir / rel
            local.parent.mkdir(parents=True, exist_ok=True)
            with open(local, 'wb') as f:
                for chunk in r.iter_content(8192):
                    f.write(chunk)
            if local.suffix == '.css':
                try:
                    css_texts.append(local.read_text(encoding='utf-8', errors='replace'))
                except:
                    pass
            return local
        except Exception:
            return None

    def process_page(page_url: str, depth: int = 0):
        nonlocal pages_crawled
        if page_url in visited or depth > 5:
            return
        visited.add(page_url)
        pages_crawled += 1

        log.info(f"  [{depth}] {page_url}")
        try:
            r = requests.get(page_url, headers=HEADERS, timeout=15)
            r.raise_for_status()
            html = r.text
        except Exception as e:
            log.warning(f"    Failed: {e}")
            return

        if not html.strip():
            return

        rel = page_to_rel_path(page_url)
        html_path = out_dir / rel
        html_path.parent.mkdir(parents=True, exist_ok=True)

        base = page_url.rstrip('/') + '/'
        new_html = html

        # Extract resources from HTML
        for pattern, attr in [
            (r'<link[^>]*rel=["\']stylesheet["\'][^>]*href=["\'](.*?)["\']', 'href'),
            (r'<link[^>]*href=["\'](.*?)["\'][^>]*rel=["\']stylesheet["\']', 'href'),
            (r'<script[^>]*src=["\'](.*?)["\']', 'src'),
            (r'<img[^>]*src=["\'](.*?)["\']', 'src'),
            (r'<link[^>]*rel=["\']preload["\'][^>]*as=["\']font["\'][^>]*href=["\'](.*?)["\']', 'href'),
            (r'<link[^>]*rel=["\'](?:icon|apple-touch-icon)["\'][^>]*href=["\'](.*?)["\']', 'href'),
        ]:
            for m in re.finditer(pattern, new_html, re.I):
                val = m.group(1)
                if any(skip in val for skip in ['data:', 'blob:', 'javascript:', 'mailto:',
                                                  'gtag', 'googletagmanager', 'gtm.js']):
                    continue
                abs_url = urljoin(base, val)
                if local := dl_asset(abs_url):
                    rel_path = str(local.relative_to(out_dir))
                    new_html = new_html.replace('"' + val + '"', '"/' + rel_path + '"', 1)

        # Write HTML
        html_path.write_text(new_html, encoding='utf-8')

        # Find internal links for deeper crawl
        if depth < 5:
            for m in re.finditer(r'<a[^>]*href=["\'](.*?)["\']', new_html, re.I):
                href = m.group(1)
                if href.startswith('#') or href.startswith('mailto:') or href.startswith('javascript:'):
                    continue
                abs_url = urljoin(base, href)
                p = urlparse(abs_url)
                if p.netloc == orig_domain and abs_url not in visited:
                    process_page(abs_url, depth + 1)

    # Start crawling
    process_page(url)

    # Combine all collected CSS
    all_css_text = '\n'.join(css_texts)
    total = len(downloaded) + pages_crawled
    tech_stack = detect_tech_stack(all_css_text + '\n'.join(
        p.read_text(encoding='utf-8', errors='replace')
        for p in out_dir.rglob('*.html')[:5]
    ) if not all_css_text else all_css_text)

    # Generate DESIGN.md
    design_md = generate_design_md(url, all_css_text, tech_stack, total)
    (out_dir / 'DESIGN.md').write_text(design_md, encoding='utf-8')

    # Generate CRAWL_REPORT.md
    (out_dir / 'CRAWL_REPORT.md').write_text(
        generate_crawl_report(url, pages_crawled, total, tech_stack),
        encoding='utf-8'
    )

    log.info(f"  Pages: {pages_crawled}, Assets: {len(downloaded)}, Total files: {total}, Stack: {tech_stack}")
    return {'pages': pages_crawled, 'assets': len(downloaded), 'total': total, 'tech_stack': tech_stack}

# ─── Download Processing ────────────────────────────────────────────────────

def process_download(dl):
    dl_id = dl.get('id')
    url = dl.get('url')
    if not url or not dl_id:
        return

    safe_name = urlparse(url).netloc.replace("www.", "")
    work_dir = DL_DIR / f'work-{safe_name}'
    zip_path = DL_DIR / f'{safe_name}.zip'

    try:
        work_dir.mkdir(parents=True, exist_ok=True)
        update_status(dl_id, status='processing', percent=10)
        stats = clone_site(url, work_dir)
        update_status(dl_id, status='processing', percent=60)

        if stats['total'] == 0:
            log.warning("  No content cloned")
            update_status(dl_id, status='failed', error='No content cloned')
            shutil.rmtree(work_dir, ignore_errors=True)
            return

        update_status(dl_id, status='packaging', percent=80)
        shutil.make_archive(str(zip_path.with_suffix('')), 'zip', work_dir)
        zip_size = zip_path.stat().st_size
        log.info(f"  ZIP: {zip_path.name} ({zip_size:,} bytes, {stats['total']} files)")

        update_status(dl_id, status='uploading', percent=90)
        try:
            upload_zip(dl_id, zip_path)
            update_status(dl_id, status='complete', percent=100,
                          file=f'{safe_name}.zip', size=zip_size,
                          tech_stack=stats.get('tech_stack', []))
            log.info(f"  Uploaded: {safe_name}.zip")
        except Exception as e:
            log.warning(f"  Upload failed (offline?): {e}")
            update_status(dl_id, status='complete_local', percent=100,
                          file=f'{safe_name}.zip', size=zip_size,
                          note='Stored locally')

    except Exception as e:
        log.error(f"  Failed: {e}")
        update_status(dl_id, status='failed', error=str(e))
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)

def upload_zip(dl_id, zip_path):
    boundary = f'----ZESDL{dl_id}'
    with open(zip_path, 'rb') as f:
        zip_data = f.read()
    body = io.BytesIO()
    body.write(f'--{boundary}\r\n'.encode())
    body.write(f'Content-Disposition: form-data; name="file"; filename="dl-{dl_id}.zip"\r\n'.encode())
    body.write(b'Content-Type: application/zip\r\n\r\n')
    body.write(zip_data)
    body.write(f'\r\n--{boundary}\r\n'.encode())
    body.write(b'Content-Disposition: form-data; name="id"\r\n\r\n')
    body.write(dl_id.encode())
    body.write(f'\r\n--{boundary}--\r\n'.encode())
    req = urllib.request.Request(
        f'{WORKER_URL}/api/download/upload', data=body.getvalue(),
        headers={'Content-Type': f'multipart/form-data; boundary={boundary}',
                 'X-Auth-Token': AUTH_TOKEN}, method='POST')
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read())

def process_queue():
    try:
        queue = api_get('/api/download/queue')
        if not queue:
            return 0
        log.info(f"Processing {len(queue)} download(s)...")
        for dl in queue:
            process_download(dl)
        api_post('/api/download/clear-queue', {})
        return len(queue)
    except Exception as e:
        log.error(f"Queue error: {e}")
        return 0

# ─── HTTP Server ────────────────────────────────────────────────────────────

class DLHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(DL_DIR), **kwargs)
    def log_message(self, fmt, *args):
        log.info(f"[HTTP] {args[0]} {args[1]} {args[2]}")
    def do_GET(self):
        p = self.path.rstrip('/')
        if p == '/health':
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'status': 'ok', 'service': 'zes-downloader-daemon',
                'dir': str(DL_DIR), 'zips': sorted([f.name for f in DL_DIR.glob('*.zip')])
            }).encode()); return
        if p == '/list':
            zips = sorted(DL_DIR.glob('*.zip'), key=lambda f: f.stat().st_mtime, reverse=True)
            items = [{'file': z.name, 'size': z.stat().st_size,
                      'modified': z.stat().st_mtime} for z in zips]
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(items).encode()); return
        super().do_GET()

def serve_http():
    server = HTTPServer(('0.0.0.0', SERVE_PORT), DLHandler)
    log.info(f"HTTP server on :{SERVE_PORT} (serving {DL_DIR})")
    server.serve_forever()

def main():
    import argparse
    parser = argparse.ArgumentParser(description='ZES Downloader Daemon v3')
    parser.add_argument('--once', action='store_true')
    parser.add_argument('--serve-only', action='store_true')
    parser.add_argument('--url', help='Clone a single URL directly')
    args = parser.parse_args()

    log.info("=" * 50)
    log.info("ZES Downloader Daemon v3")
    log.info(f"  Worker: {WORKER_URL}")
    log.info(f"  Store:  {DL_DIR}")
    log.info(f"  Serve:  :{SERVE_PORT}")
    log.info("=" * 50)

    if args.url:
        dl = {'id': hashlib.md5(args.url.encode()).hexdigest()[:16], 'url': args.url}
        process_download(dl)
        return
    if args.serve_only:
        serve_http(); return

    http_thread = threading.Thread(target=serve_http, daemon=True)
    http_thread.start()
    log.info("HTTP server started in background")
    if args.once:
        count = process_queue()
        log.info(f"Processed {count} download(s)"); return

    while True:
        try:
            count = process_queue()
            if count == 0:
                log.info("Idle. Checking again in 30s...")
            time.sleep(30)
        except KeyboardInterrupt:
            log.info("Shutting down..."); break
        except Exception as e:
            log.error(f"Cycle error: {e}"); time.sleep(30)

if __name__ == '__main__':
    main()
